### ISSUE TITLE
Create main screen component

### ISSUE THREAD

**Issue by BabkinAV** [chingu-voyages/v37-geckos-team-07#17]
**__Major User Stories/tasks__**
- [ ] Total current balance
- [ ] Add / remove incomes
- [ ] Add / remove expenses
- [ ] Dashboard toggle button
