### ISSUE TITLE
Create dashboard component

### ISSUE THREAD

**Issue by BabkinAV** [chingu-voyages/v37-geckos-team-07#18]
**__Feature Description__**
Pull data from database and show charts

**Possible charts**
- [ ] Incomes by type
- [ ] Incomes by date
- [ ] Expenses by type
- [ ] Expenses by date
- [ ] Pie chart incomes vs. expenses
- [ ] Mobile view
